#!/bin/bash

# 1. Detect Distro
if [ -f /etc/os-release ]; then
    . /etc/os-release
    case "$ID" in
        arch)   DISTRO_ICON="" ;;
        fedora) DISTRO_ICON="" ;;
        ubuntu) DISTRO_ICON="" ;;
        opensuse*)  DISTRO_ICON="" ;;
        *)      DISTRO_ICON="" ;;
    esac
else
    DISTRO_ICON=""
fi

# 2. Load Git Prompt (Local Copy)
if [ -f ~/.git-prompt.sh ]; then
    source ~/.git-prompt.sh
fi

# 3. Configure Git Status
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto"

# 4. Define Colors
# \[ ... \] tells bash these characters don't take up space (prevents wrapping bugs)
RESET="\[\e[0m\]"
GREEN="\[\e[32m\]"
BLUE="\[\e[34m\]"

# 5. Build PS1
# We step out of the single quotes ' ' to insert variables like $GREEN
export PS1='('$DISTRO_ICON')'$GREEN'\u'$RESET'@'$BLUE'\h'$RESET'[\w]$(__git_ps1 " (%s)")\n-> '
